### ISSUE TITLE
Provider segfaults when running into HCP API rate limit

### ISSUE THREAD

**Issue by fhemberger** [hashicorp/terraform-provider-hcp#727]
### Terraform Version and Provider Version

```
Terraform version: v1.7.0
HCP provider version: 0.80
```

### Affected Resource(s)

* Discovered while using `hcp_vault_secrets_secret`, but affects all resources

### Steps to Reproduce

We are using the provider to initially populate Vault Secrets with secrets for various existing apps (round about 500 resources) to help with our migration. 

The provider seems to ignore the rate limit headers of the HPC API and segfaults once the limit is reached:

```
HTTP/2.0 429 Too Many Requests
Access-Control-Allow-Credentials: true
Cache-Control: no-store, max-age=0
Content-Type: application/json
Date: Thu, 18 Jan 2024 09:57:03 GMT
Grpc-Metadata-Content-Type: application/grpc
Server: envoy
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 6
X-Ratelimit-Limit: 200
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 60

{"code":8,"message":"this request has exceeded the rate limit of 200 requests per minute for your org, try again in 60 seconds","details":[]}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103b22798]
goroutine 409 [running]:
github.com/hashicorp/terraform-provider-hcp/internal/provider/vaultsecrets.(*resourceVaultsecretsSecret).Read(0x14000bce000, {0x1040bd148, 0x14000b898c0}, {{{{0x1040c2280, 0x14000a49f50}, {0x103ea08a0, 0x14000a49e00}}, {0x1040c4198, 0x14000914c30}}, 0x140006dc008, ...}, ...)
	github.com/hashicorp/terraform-provider-hcp/internal/provider/vaultsecrets/resource_vault_secrets_secret.go:147 +0x258
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x14000184b00, {0x1040bd148, 0x14000b898c0}, 0x14000b89950, 0x14000a554f0)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_readresource.go:101 +0x514
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x14000184b00, {0x1040bd148?, 0x14000b897a0?}, 0x14000b98480)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1040bd180?, {0x1040bd148?, 0x14000b894a0?}, 0x14000b98480)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400011e640, {0x1040bd148?, 0x14000ab0fc0?}, 0x140001317a0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x390
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1040699e0?, 0x1400011e640}, {0x1040bd148, 0x14000ab0fc0}, 0x1400050b980, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400025ee00, {0x1040bd148, 0x14000ab0f00}, {0x1040c2e18, 0x140001024e0}, 0x14000aa85a0, 0x14000273ef0, 0x104b6e808, 0x0)
	google.golang.org/grpc@v1.60.1/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x1400025ee00, {0x1040c2e18, 0x140001024e0}, 0x14000aa85a0)
	google.golang.org/grpc@v1.60.1/server.go:1783 +0xc44
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.1/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
	google.golang.org/grpc@v1.60.1/server.go:1027 +0x138

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103b22798]
goroutine 104 [running]:
github.com/hashicorp/terraform-provider-hcp/internal/provider/vaultsecrets.(*resourceVaultsecretsSecret).Read(0x14000b4c000, {0x1040bd148, 0x14000b0af30}, {{{{0x1040c2280, 0x14000b0bdd0}, {0x103ea08a0, 0x14000b0bc80}}, {0x1040c4198, 0x14000914c30}}, 0x14000b4c010, ...}, ...)
	github.com/hashicorp/terraform-provider-hcp/internal/provider/vaultsecrets/resource_vault_secrets_secret.go:147 +0x258
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x14000184b00, {0x1040bd148, 0x14000b0af30}, 0x14000b0b020, 0x14000b4b4f0)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_readresource.go:101 +0x514
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x14000184b00, {0x1040bd148?, 0x14000b0ae10?}, 0x14000b0e240)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1040bd180?, {0x1040bd148?, 0x14000b0ab10?}, 0x14000b0e240)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400011e640, {0x1040bd148?, 0x14000b0a330?}, 0x140000a07e0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x390
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1040699e0?, 0x1400011e640}, {0x1040bd148, 0x14000b0a330}, 0x14000b20000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400025ee00, {0x1040bd148, 0x14000b0a2a0}, {0x1040c2e18, 0x140001024e0}, 0x14000b1a120, 0x14000273ef0, 0x104b6e808, 0x0)
	google.golang.org/grpc@v1.60.1/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x1400025ee00, {0x1040c2e18, 0x140001024e0}, 0x14000b1a120)
	google.golang.org/grpc@v1.60.1/server.go:1783 +0xc44
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.1/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
	google.golang.org/grpc@v1.60.1/server.go:1027 +0x138
provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/hcp/0.80.0/darwin_arm64/terraform-provider-hcp_v0.80.0_x5 pid=2267 error="exit status 2"
```

We kind of "got around" that issue by setting `terraform apply -parallelism=1`, which made execution terribly slow, but this kind of issue should be handled by the provider itself IMHO.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by fhemberger** [comment]
pinging @averche
